name: "Update Jetbrains Products"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update_jetbrains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./nixos/system-packages/jetbrains/update.py

      # check if versions.json has changed
      - name: Check for File Changes
        id: version_file_changed
        shell: bash
        run: |
          GIT_STATUS="$(git status --porcelain ./nixos/system-packages/jetbrains/versions.json)"
          
          echo "::set-output name=git_status::$GIT_STATUS"

      # Create pull request
      - name: Create Pull Request
        if: ${{ steps.version_file_changed.outputs.git_status != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="jetbrains-update"
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git checkout -b $BRANCH
          
          git add ./nixos/system-packages/jetbrains/versions.json
          git commit -m "Update jetbrains product versions"
          git push --set-upstream origin $BRANCH
          gh pr create \
            --title "Update Jetbrains Product Versions" \
            --body "Current pull request contains the updated versions.json for jetbrains products." \
            --base main \
            --head $BRANCH
          
          gh pr merge $BRANCH --delete-branch --auto --rebase
